In [1]:
%run constants.py

In [2]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FUNCTIONS/load_functions"

SyntaxError: invalid syntax (DustModelFunctions.py, line 116)

In [3]:
df_water_ice = pd.read_csv(m_data_folder_path + "m_table_water_ice.txt",
                 delim_whitespace=True,
                 header = None)

df_water_ice.columns = ["wavelength (microns)", "m_re", "m_im"]

df_water_ice

     wavelength (microns)    m_re      m_im
0            4.430000e-02  0.8228  0.164000
1            4.510000e-02  0.8250  0.173000
2            4.590000e-02  0.8255  0.183000
3            4.680000e-02  0.8258  0.195000
4            4.770000e-02  0.8263  0.208000
..                    ...     ...       ...
481          2.400000e+05  1.7861  0.000107
482          3.400000e+05  1.7861  0.000131
483          5.400000e+05  1.7861  0.000189
484          1.000000e+06  1.7861  0.000335
485          2.000000e+06  1.7861  0.000660

[486 rows x 3 columns]

In [4]:
df_tro = pd.read_csv(m_data_folder_path + "m_table_troilite.txt",
                 delim_whitespace=True,
                 header = None)

df_tro.columns = ["wavelength (microns)", "m_re", "m_im"]

df_tro

     wavelength (microns)      m_re       m_im
0                   0.100    4.2529    0.75934
1                   0.105    4.2937    0.77511
2                   0.125    4.4103    0.82966
3                   0.140    4.4843    0.85835
4                   0.155    4.5454    0.87669
..                    ...       ...        ...
108              3000.000   12.5590   20.32400
109              5700.000   15.2160   36.81500
110              9600.000   20.7710   58.61600
111             30000.000   66.3270  164.90000
112            100000.000  362.5000  300.00000

[113 rows x 3 columns]

In [6]:
df_as = pd.read_csv(
    m_data_folder_path + "m_table_astronomical_silicate.txt",
    delim_whitespace=True,
    header=None,
    skiprows=10,  # adjust this number based on how many lines of header there are
    comment='#'   # in case lines start with '#' for comments
)

df_as.columns = ["wavelength (microns)", "Re_eps_minus_1", "Im_eps", "Re_m_minus_1", "Im_m"]

# Now compute m_re and m_im (actual refractive index n, k):
df_as["m_re"] = df_as["Re_m_minus_1"] + 1.0
df_as["m_im"] = df_as["Im_m"]

# If you want, keep only columns you need:
df_as_trim = df_as[["wavelength (microns)", "m_re", "m_im"]]

df_as_trim.head()

   wavelength (microns)    m_re      m_im
0                988.55  3.4080  0.050199
1                977.24  3.4080  0.050781
2                966.05  3.4080  0.051369
3                954.99  3.4081  0.051964
4                944.06  3.4081  0.052567

In [ ]:
df_ro = pd.read_csv(m_data_folder_path + "m_table_ro.txt",
                 delim_whitespace=True,
                 header = None)

df_ro.columns = ["wavelength (microns)", "m_re", "m_im"]

df_ro

In [ ]:
lambda_band1_micron  = 7.0  * 1000  # mm to microns
lambda_band3_micron  = 3.1  * 1000  # mm to microns
lambda_band7_micron  = 0.87 * 1000  # mm to microns
lambda_band10_micron = 0.34 * 1000  # mm to microns

In [ ]:
lambda_targets = [lambda_band1_micron, lambda_band3_micron, lambda_band7_micron, lambda_band10_micron]

In [ ]:
m_re_interp = []
m_im_interp = []


for i in range(4):
    m_re = np.interp(lambda_targets[i], df_water_ice["wavelength (microns)"], df_water_ice["m_re"])
    m_im = np.interp(lambda_targets[i], df_water_ice["wavelength (microns)"], df_water_ice["m_im"])
    
    m_re_interp.append(m_re)
    m_im_interp.append(m_im)

In [ ]:
m_complex_interp = [n + 1j * k for n, k in zip(m_re_interp, m_im_interp)]

In [ ]:
m_complex_interp[0]